# Generated by Django 3.2.24 on 2024-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='speciality',
            field=models.CharField(default='Speciality', max_length=254),
            preserve_default=False,
        ),
    ]
