# Generated by Django 3.2.24 on 2024-03-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coach_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
    ]
